### ISSUE TITLE
entityremoved not being raised

### ISSUE THREAD

**Issue by ErikNoren** [ErikNoren/entitypicker#6]
The entityadded event fires but entityremoved does not.

**Comment by jpock76** [comment]
Remove entityContainer AFTER calling the trigger.

	function deleteEntity(entityContainer) {
		var $input = entityContainer.find("input");
		var $this = this;

		entityRemovedEvent.value = entityContainer.find("span.entityDisplay")[0].attributes[0].value; //$input.val();
		entityRemovedEvent.inputName = $input.attr("name");


		$this.trigger(entityRemovedEvent);
	    entityContainer.remove();

	}

**Comment by ErikNoren** [comment]
I pulled down the project, ran the demo and - after updating the Google CDN links which aren't offered over HTTP anymore - I was able to replicate the issue. Swapping the lines resolved it. Committed the change to the JS and demo HTML as well as updated the Readme for this new 0.5.5 bug fix version.

Thank you for spotting the issue!
