### ISSUE TITLE
Adding Entities

### ISSUE THREAD

**Issue by jpock76** [ErikNoren/entitypicker#7]
Per the description it says " you can add entities programmatically in order to restore values that have previously been saved (for use on an edit screen, for instance".  I have been having trouble figuring out how to do this and there is not an example in the demo. Basically I am loading up the control and populating it values as entity objects.  These are not necessarily data bound to any search.  There is an addEntities function although I am unsure how to call it. Can you help me out?

**Comment by ErikNoren** [comment]
Sure. You will either have a single object with 2 members: value and label or an array of objects containing value and label. You add them to the picker with something like $("#depart").entitypicker("addEntities", entities);

Using the demo page, if you open the browser console you can try the following lines to see it work.

var newEntities = [ {'label':'Test1','value':1},{'label':'Test2','value':2} ];
$("#depart").entitypicker("addEntities",newEntities);

This expects the element to already be initialized before trying to call add*, delete*, etc. so if you're restoring data on page load, make sure you initialize the control first. I believe you'll get an error in the console log letting you know if you don't.

**Comment by jpock76** [comment]
That works great. Thank you!
